sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - 'stable'
  - 'node'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/